name: backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend_ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [19.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: install dependencies
        run: pnpm install
      - name: build
        run: pnpm run build
      - name: linter
        run: pnpm run lint
      - name: format
        run: pnpm run format
